version: '1.0'
services:
  web:
    image: bankapp
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
